# Generated by Django 4.0.4 on 2022-05-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_type',
            new_name='user_type',
        ),
    ]
